// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlIXDQRrEcf1wNxmf6JaehHXeUMjIkms',
    appId: '1:28075736253:web:2bdd5b8a8489af30ad8bd4',
    messagingSenderId: '28075736253',
    projectId: 'university-63fda',
    authDomain: 'university-63fda.firebaseapp.com',
    storageBucket: 'university-63fda.appspot.com',
    measurementId: 'G-EVB3V1T7JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPY82V4IQcDNScRPbMfJA3lsBoar-KjDc',
    appId: '1:28075736253:android:e80fe510a8985ba7ad8bd4',
    messagingSenderId: '28075736253',
    projectId: 'university-63fda',
    storageBucket: 'university-63fda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zd0X5OrcAm9FUTKY3nd_houHrrmTXyU',
    appId: '1:28075736253:ios:b5be5c5dae8c38c1ad8bd4',
    messagingSenderId: '28075736253',
    projectId: 'university-63fda',
    storageBucket: 'university-63fda.appspot.com',
    iosClientId: '28075736253-6tud3p89vgghqo5rn7ljoci29lk78fv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.university',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zd0X5OrcAm9FUTKY3nd_houHrrmTXyU',
    appId: '1:28075736253:ios:b5be5c5dae8c38c1ad8bd4',
    messagingSenderId: '28075736253',
    projectId: 'university-63fda',
    storageBucket: 'university-63fda.appspot.com',
    iosClientId: '28075736253-6tud3p89vgghqo5rn7ljoci29lk78fv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.university',
  );
}
